### ISSUE TITLE
IAM trace Error: No request ID found for iam

### ISSUE THREAD

**Issue by orenbenya** [iann0036/former2#213]
When running the command for IAM service I keep getting this error, although I do get the file with the items in it.
I run: 
`former2 generate --services "IAM" --region "region" --profile "profile" --output-cloudformation "cfn.yml" --proxy "http://proxy:port"`

Server version: Red Hat Enterprise Linux Server release 7.4 (Maipo)
AWS CLI: aws-cli/2.0.22 Python/3.7.3 Linux/3.10.0-693.21.1.el7.x86_64 botocore/2.0.0dev26

NPM version:
`{
  npm: '8.5.1',
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}`

`Trace: No request ID found for iam
    at getResourceName (eval at <anonymous> (/usr/lib/node_modules/former2/main.js:118:1), <anonymous>:1838:17)
    at eval (eval at <anonymous> (/usr/lib/node_modules/former2/main.js:122:5), <anonymous>:1285:26)
    at eval (eval at <anonymous> (/usr/lib/node_modules/former2/main.js:118:1), <anonymous>:4443:25)
    at Array.forEach (<anonymous>)
    at eval (eval at <anonymous> (/usr/lib/node_modules/former2/main.js:118:1), <anonymous>:4441:39)
    at Array.forEach (<anonymous>)
    at performF2Mappings (eval at <anonymous> (/usr/lib/node_modules/former2/main.js:118:1), <anonymous>:4427:13)
    at main (/usr/lib/node_modules/former2/main.js:268:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by iann0036** [comment]
Hey @orenbenya,

Thanks for raising!

I've fixed this issue and it should be available if you update to version 0.2.63.

**Comment by orenbenya** [comment]
Hi,
Not sure if it happened due to the current fix,
But now this happened.
Just a side note, I've ran this more than 400 time without any issue, after the upgrade ,this happened.
It happened on the **EC2** service.

`0% (0/1 services completed)node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was{
  code: 'ERR_UNHANDLED_REJECTION'
}`

**Comment by iann0036** [comment]
Hey @orenbenya,

I've tested on my side and confirmed that 0.2.63 seems to be working as intended, and the updates should be fairly benign. Could this possibly be an issue with how the application performed its upgrade?

If you fully uninstall and reinstall from scratch, do you still receive the same issue?

**Comment by orenbenya** [comment]
It seems like a bad update, you are correct.
Now it works without an issue.
Thank you.
