### ISSUE TITLE
RequestLimitExceeded exceptions in error logs

### ISSUE THREAD

**Issue by Vardominator** [iann0036/former2#89]
I'm seeing a large number of `RequestLimitExceeded` exceptions in the logs. Here is an example:
```
Trace: RequestLimitExceeded: Request limit exceeded.
    at Request.extractError (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/vbarsegyan/former2/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'RequestLimitExceeded',
  time: 2020-08-19T10:01:39.095Z,
  requestId: 'e617cd80-eee2-4021-a1db-7e97ab982bb4',
  statusCode: 503,
  retryable: true
}
```

There is some inconsistency in the number resources that are being generated at every run. I ran
`node /former2/cli/main.js generate --region us-east-1 --output-terraform /tmp/backup.tf` once a day for 6 days in a row and the files sizes varied as follows: 1.4MB, 459KB, 526KB, 556KB, 529KB, 440KB.
Is this inconsistency somehow tied to the AWS request limit? If so, would it be possible to limit the number asynchronous API requests such that all resources are captured at every run?

Reference: https://github.com/iann0036/former2/issues/86 (thanks again!)

**Comment by iann0036** [comment]
Hey @Vardominator,

Thanks for the report. I've added that error code to the exponential backoff logic, so it should safely retry when it hits that code (version 0.2.48).

I'm not entirely convinced that'll be the whole cause of that discrepancy (I've seen it myself and wondered). If you still see the difference after a few runs, see if you can identify if it's specific resource types and let me know.

Cheers!

**Comment by Vardominator** [comment]
It's common for EC2 resources not to show up at all.

**Comment by Vardominator** [comment]
Hey @iann0036. Did you have a chance to look into this? I'm happy to help in any way that I can.

**Comment by iann0036** [comment]
Hey @Vardominator,

Sorry for the confusion. I did add some error handling logic in version 0.2.48, so if you're running that specific version, could you check your latest runs to see if the resources are still varied?

If they are, can you re-confirm if you're still seeing the `RequestLimitExceeded` trace in the logs and if the missing resources are all EC2 related?

**Comment by Vardominator** [comment]
Thanks! Sorry, I thought I had the latest version deployed.

I just updated and I'm no longer seeing that exception in the logs! Let me test for a days and get back to you.

**Comment by Vardominator** [comment]
Hey @iann0036,

Everything works like a charm! Feel free to close this ticket.

**Comment by iann0036** [comment]
Great. Thanks again for your help!
